"""Initial schema

Revision ID: 20260423_0001
Revises: 
Create Date: 2026-04-23

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models import AccountType, AuditStatus, NotificationType


# revision identifiers, used by Alembic.
revision = '20260423_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    postgresql.ENUM(AccountType, name="shared_account_type").create(bind, checkfirst=True)
    postgresql.ENUM(AuditStatus, name="shared_audit_status").create(bind, checkfirst=True)
    postgresql.ENUM(NotificationType, name="notification_type_enum").create(bind, checkfirst=True)

    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('account_type', postgresql.ENUM(AccountType, name="shared_account_type", create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('instrument_key', sa.String(length=255), nullable=False),
    sa.Column('instrument_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('place_type', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('est_auditors', sa.Integer(), nullable=True),
    sa.Column('auditor_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('account_type', postgresql.ENUM(AccountType, name="shared_account_type", create_type=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verification_token_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_users_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True)
    op.create_table('auditor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('auditor_code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('age_range', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_auditor_profiles_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auditor_profiles_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditor_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_auditor_profiles_user_id'))
    )
    op.create_index(op.f('ix_auditor_profiles_auditor_profiles_account_id'), 'auditor_profiles', ['account_id'], unique=False)
    op.create_index(op.f('ix_auditor_profiles_auditor_profiles_auditor_code'), 'auditor_profiles', ['auditor_code'], unique=True)
    op.create_index(op.f('ix_auditor_profiles_auditor_profiles_email'), 'auditor_profiles', ['email'], unique=True)
    op.create_table('manager_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_manager_invites_accepted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_manager_invites_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_manager_invites_invited_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_manager_invites_token_hash'))
    )
    op.create_index(op.f('ix_manager_invites_manager_invites_accepted_by_user_id'), 'manager_invites', ['accepted_by_user_id'], unique=False)
    op.create_index(op.f('ix_manager_invites_manager_invites_account_id'), 'manager_invites', ['account_id'], unique=False)
    op.create_index(op.f('ix_manager_invites_manager_invites_email'), 'manager_invites', ['email'], unique=False)
    op.create_index(op.f('ix_manager_invites_manager_invites_invited_by_user_id'), 'manager_invites', ['invited_by_user_id'], unique=False)
    op.create_table('manager_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_manager_profiles_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_manager_profiles_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_manager_profiles_user_id'))
    )
    op.create_index('ix_manager_profiles_account_primary_true', 'manager_profiles', ['account_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index(op.f('ix_manager_profiles_manager_profiles_account_id'), 'manager_profiles', ['account_id'], unique=False)
    op.create_index(op.f('ix_manager_profiles_manager_profiles_email'), 'manager_profiles', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('notification_type', postgresql.ENUM(NotificationType, name="notification_type_enum", create_type=False), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('place_types', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('est_places', sa.Integer(), nullable=True),
    sa.Column('est_auditors', sa.Integer(), nullable=True),
    sa.Column('auditor_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_projects_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_projects_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_projects_account_id'), 'projects', ['account_id'], unique=False)
    op.create_index(op.f('ix_projects_projects_created_by_user_id'), 'projects', ['created_by_user_id'], unique=False)
    op.create_table('auditor_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_auditor_invites_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditor_profiles.id'], name=op.f('fk_auditor_invites_auditor_id_auditor_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_auditor_invites_invited_by_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditor_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auditor_invites_token_hash'))
    )
    op.create_index(op.f('ix_auditor_invites_auditor_invites_account_id'), 'auditor_invites', ['account_id'], unique=False)
    op.create_index(op.f('ix_auditor_invites_auditor_invites_auditor_id'), 'auditor_invites', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_auditor_invites_auditor_invites_email'), 'auditor_invites', ['email'], unique=False)
    op.create_index(op.f('ix_auditor_invites_auditor_invites_invited_by_user_id'), 'auditor_invites', ['invited_by_user_id'], unique=False)
    op.create_table('project_places',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_project_places_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_places_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'place_id', name=op.f('pk_project_places'))
    )
    op.create_table('yee_audit_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('participant_info_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('responses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditor_profiles.id'], name=op.f('fk_yee_audit_submissions_auditor_id_auditor_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_yee_audit_submissions_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yee_audit_submissions'))
    )
    op.create_index(op.f('ix_yee_audit_submissions_yee_audit_submissions_auditor_id'), 'yee_audit_submissions', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_yee_audit_submissions_yee_audit_submissions_place_id'), 'yee_audit_submissions', ['place_id'], unique=False)
    op.create_table('auditor_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auditor_profile_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_profile_id'], ['auditor_profiles.id'], name=op.f('fk_auditor_assignments_auditor_profile_id_auditor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_auditor_assignments_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'place_id'], ['project_places.project_id', 'project_places.place_id'], name='fk_auditor_assignments_project_place_pair', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_auditor_assignments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditor_assignments')),
    sa.UniqueConstraint('auditor_profile_id', 'project_id', 'place_id', name='uq_auditor_assignments_auditor_project_place')
    )
    op.create_index(op.f('ix_auditor_assignments_auditor_assignments_auditor_profile_id'), 'auditor_assignments', ['auditor_profile_id'], unique=False)
    op.create_index(op.f('ix_auditor_assignments_auditor_assignments_place_id'), 'auditor_assignments', ['place_id'], unique=False)
    op.create_index(op.f('ix_auditor_assignments_auditor_assignments_project_id'), 'auditor_assignments', ['project_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('auditor_profile_id', sa.UUID(), nullable=False),
    sa.Column('audit_code', sa.String(length=120), nullable=False),
    sa.Column('instrument_key', sa.String(length=80), nullable=True),
    sa.Column('instrument_version', sa.String(length=40), nullable=True),
    sa.Column('status', postgresql.ENUM(AuditStatus, name="shared_audit_status", create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('summary_score', sa.Float(), nullable=True),
    sa.Column('responses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_profile_id'], ['auditor_profiles.id'], name=op.f('fk_audits_auditor_profile_id_auditor_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_audits_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'place_id'], ['project_places.project_id', 'project_places.place_id'], name='fk_audits_project_place_pair', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audits_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audits')),
    sa.UniqueConstraint('project_id', 'place_id', 'auditor_profile_id', name='uq_audits_project_place_auditor')
    )
    op.create_index(op.f('ix_audits_audits_audit_code'), 'audits', ['audit_code'], unique=True)
    op.create_index(op.f('ix_audits_audits_auditor_profile_id'), 'audits', ['auditor_profile_id'], unique=False)
    op.create_index(op.f('ix_audits_audits_place_id'), 'audits', ['place_id'], unique=False)
    op.create_index(op.f('ix_audits_audits_project_id'), 'audits', ['project_id'], unique=False)
    op.create_table('playspace_audit_contexts',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=True),
    sa.Column('draft_progress_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], name='fk_ps_context_audit', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_playspace_audit_contexts'))
    )
    op.create_table('playspace_audit_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('section_key', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], name='fk_ps_audit_section_audit', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playspace_audit_sections')),
    sa.UniqueConstraint('audit_id', 'section_key', name='uq_playspace_audit_sections_audit_section')
    )
    op.create_index(op.f('ix_playspace_audit_sections_playspace_audit_sections_audit_id'), 'playspace_audit_sections', ['audit_id'], unique=False)
    op.create_table('playspace_pre_audit_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('selected_value', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], name='fk_ps_pre_audit_answer_audit', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playspace_pre_audit_answers')),
    sa.UniqueConstraint('audit_id', 'field_key', 'selected_value', name='uq_playspace_pre_audit_answers_audit_field_value')
    )
    op.create_index(op.f('ix_playspace_pre_audit_answers_playspace_pre_audit_answers_audit_id'), 'playspace_pre_audit_answers', ['audit_id'], unique=False)
    op.create_table('playspace_question_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['playspace_audit_sections.id'], name='fk_ps_question_response_section', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playspace_question_responses')),
    sa.UniqueConstraint('section_id', 'question_key', name='uq_playspace_question_responses_section_question')
    )
    op.create_index(op.f('ix_playspace_question_responses_playspace_question_responses_section_id'), 'playspace_question_responses', ['section_id'], unique=False)
    op.create_table('playspace_scale_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_response_id', sa.UUID(), nullable=False),
    sa.Column('scale_key', sa.String(length=40), nullable=False),
    sa.Column('option_key', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_response_id'], ['playspace_question_responses.id'], name='fk_ps_scale_answer_question_response', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playspace_scale_answers')),
    sa.UniqueConstraint('question_response_id', 'scale_key', name='uq_playspace_scale_answers_question_scale')
    )
    op.create_index(op.f('ix_playspace_scale_answers_playspace_scale_answers_question_response_id'), 'playspace_scale_answers', ['question_response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playspace_scale_answers_playspace_scale_answers_question_response_id'), table_name='playspace_scale_answers')
    op.drop_table('playspace_scale_answers')
    op.drop_index(op.f('ix_playspace_question_responses_playspace_question_responses_section_id'), table_name='playspace_question_responses')
    op.drop_table('playspace_question_responses')
    op.drop_index(op.f('ix_playspace_pre_audit_answers_playspace_pre_audit_answers_audit_id'), table_name='playspace_pre_audit_answers')
    op.drop_table('playspace_pre_audit_answers')
    op.drop_index(op.f('ix_playspace_audit_sections_playspace_audit_sections_audit_id'), table_name='playspace_audit_sections')
    op.drop_table('playspace_audit_sections')
    op.drop_table('playspace_audit_contexts')
    op.drop_index(op.f('ix_audits_audits_project_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_audits_place_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_audits_auditor_profile_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_audits_audit_code'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_auditor_assignments_auditor_assignments_project_id'), table_name='auditor_assignments')
    op.drop_index(op.f('ix_auditor_assignments_auditor_assignments_place_id'), table_name='auditor_assignments')
    op.drop_index(op.f('ix_auditor_assignments_auditor_assignments_auditor_profile_id'), table_name='auditor_assignments')
    op.drop_table('auditor_assignments')
    op.drop_index(op.f('ix_yee_audit_submissions_yee_audit_submissions_place_id'), table_name='yee_audit_submissions')
    op.drop_index(op.f('ix_yee_audit_submissions_yee_audit_submissions_auditor_id'), table_name='yee_audit_submissions')
    op.drop_table('yee_audit_submissions')
    op.drop_table('project_places')
    op.drop_index(op.f('ix_auditor_invites_auditor_invites_invited_by_user_id'), table_name='auditor_invites')
    op.drop_index(op.f('ix_auditor_invites_auditor_invites_email'), table_name='auditor_invites')
    op.drop_index(op.f('ix_auditor_invites_auditor_invites_auditor_id'), table_name='auditor_invites')
    op.drop_index(op.f('ix_auditor_invites_auditor_invites_account_id'), table_name='auditor_invites')
    op.drop_table('auditor_invites')
    op.drop_index(op.f('ix_projects_projects_created_by_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_projects_account_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_manager_profiles_manager_profiles_email'), table_name='manager_profiles')
    op.drop_index(op.f('ix_manager_profiles_manager_profiles_account_id'), table_name='manager_profiles')
    op.drop_index('ix_manager_profiles_account_primary_true', table_name='manager_profiles', postgresql_where=sa.text('is_primary = true'))
    op.drop_table('manager_profiles')
    op.drop_index(op.f('ix_manager_invites_manager_invites_invited_by_user_id'), table_name='manager_invites')
    op.drop_index(op.f('ix_manager_invites_manager_invites_email'), table_name='manager_invites')
    op.drop_index(op.f('ix_manager_invites_manager_invites_account_id'), table_name='manager_invites')
    op.drop_index(op.f('ix_manager_invites_manager_invites_accepted_by_user_id'), table_name='manager_invites')
    op.drop_table('manager_invites')
    op.drop_index(op.f('ix_auditor_profiles_auditor_profiles_email'), table_name='auditor_profiles')
    op.drop_index(op.f('ix_auditor_profiles_auditor_profiles_auditor_code'), table_name='auditor_profiles')
    op.drop_index(op.f('ix_auditor_profiles_auditor_profiles_account_id'), table_name='auditor_profiles')
    op.drop_table('auditor_profiles')
    op.drop_index(op.f('ix_users_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('places')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_accounts_accounts_email'), table_name='accounts')
    op.drop_table('accounts')

    bind = op.get_bind()
    postgresql.ENUM(NotificationType, name="notification_type_enum").drop(bind, checkfirst=True)
    postgresql.ENUM(AuditStatus, name="shared_audit_status").drop(bind, checkfirst=True)
    postgresql.ENUM(AccountType, name="shared_account_type").drop(bind, checkfirst=True)
    # ### end Alembic commands ###

